import React from "react";

function LimitedEdition() {
  return (
    <div className="bg-white relative pt-[7vw]">
      <div className="flex w-full items-center justify-center ">
        <h1 className="vp relative top-0 w-fit h-auto py-4 justify-center flex bg-[#000000] items-center bg-clip-text text-[7vw] leading-none text-transparent text-center select-auto">
          {/* Limited Edition */}
          From any Chain to any Metaverse
        </h1>
      </div>
      <div className="w-full mt-[-5vw] relative z-10 flex justify-center items-center">
        <img
          src="assets/avatar/avatar02.png"
          className="w-[38%] relative -mr-[10%]"
        />
        <img src="assets/avatar/avatar03.png" className="w-[31%] relative z-10" />
        <img
          src="assets/avatar/avatar04.png"
          className="w-[31%] relative -ml-[8%]"
        />
      </div>
      {/* 1st */}
      <div className="text-[8px] sm:text-[14px] md:text-[15px] lg:text-[18px] xl:text-[22px] max-sm:leading-[10px] max-lg:leading-[18px] absolute bottom-[3vw] sm:bottom-[5vw] md:bottom-[10vw] w-[140px] sm:w-[260px] md:w-[300px] lg:w-[370px] xl:w-[470px] left-2 sm:left-3 lg:left-[5%] z-20 text-black ">
        <div className="relative top-0 right-0 bottom-0 left-0 z-20">
          <img src="assets/images/bg-1.png" className=" relative w-full" />
          {[1, 2, 3, 4, 5].map((_, index) => (
            <img
              key={index}
              src="assets/images/bg-1.png"
              className="absolute top-0 z-0 w-full"
            />
          ))}
          <p className="myfont-2 relative z-10 -mt-[75px] sm:-mt-[126px] md:-mt-[145px] lg:-mt-[190px] xl:-mt-[240px] px-3 md:px-7 ">
            Beamit AI is your go-to service for metaverse-ready 3D avatars
            generated by a decentralized AI. Secure your spot now to beam your
            favourite PFP into the open metaverse!
          </p>
        </div>
      </div>
      {/* 2nd */}
      {/* <div className="text-[8px] sm:text-[14px] md:text-[15px] lg:text-[18px] xl:text-[22px] max-sm:leading-[10px] max-lg:leading-[18px] absolute top-[20vw] w-[120px] sm:w-[190px] md:w-[210px] lg:w-[260px] xl:w-[300px] right-2 md:right-5 lg:right-[5%] z-20 text-black ">
        <div className="relative top-0 right-0 bottom-0 left-0 z-20">
          <img src="assets/images/bg-3.png" className=" relative w-full" />
          <img
            src="assets/images/bg-3.png"
            className="absolute top-0 z-0 w-full"
          />
          <p className="myfont-2 relative z-10 -mt-[45px] sm:-mt-[77px] md:-mt-[80px] lg:-mt-[110px] xl:-mt-[130px] pl-4 sm:pl-7">
            An Interdimensional Teleport Device for the Open Metaverse
          </p>
        </div>
      </div> */}
      {/* 3rd */}
      <div className="text-[7px] sm:text-[12px] md:text-[15px] lg:text-[18px] xl:text-[21px] absolute top-[60vw] md:top-[50vw] w-[160px] sm:w-[280px] md:w-[350px] lg:w-[420px] xl:w-[485px] right-2 md:right-5 lg:right-[5%] z-20  text-white">
        <div className="relative top-0 right-0 bottom-0 left-0 z-20">
          <img src="assets/images/bg-2.png" className=" relative w-full" />
          {[1, 2, 3, 4].map((_, index) => (
            <img
              key={index}
              src="assets/images/bg-2.png"
              className="absolute top-0 z-0 w-full"
            />
          ))}
          <div className="myfont-2 relative z-10 -mt-[75px] sm:-mt-[132px] md:-mt-[165px] lg:-mt-[200px] xl:-mt-[228px] pl-3 pr-1 sm:pr-0 sm:pl-7 md:pl-10">
            {/* <li>from any chain</li>
            <li> to any metaverse</li>
            <li>choose your style while maintaining traits</li>
            <li>at a fraction of cost ever before possible </li>
            <li>generated within minutes</li> */}
            <div className="flex items-start gap-2">
              <div className="size-[3px] sm:size-1 lg:size-[5px] rounded-full mt-[4px] sm:mt-[9px] lg:mt-[13px] xl:mt-4 bg-white"></div>
              <p>choose your style while maintaining traits</p>
            </div>
            <div className="flex items-start gap-2">
              <div className="size-[3px] sm:size-1 lg:size-[5px] rounded-full mt-[4px] sm:mt-[9px] lg:mt-[13px] xl:mt-4 bg-white"></div>
              <p>at a fraction of cost ever before possible</p>
            </div>
            <div className="flex items-start gap-2">
              <div className="size-[3px] sm:size-1 lg:size-[5px] rounded-full mt-[4px] sm:mt-[9px] lg:mt-[13px] xl:mt-4 bg-white"></div>
              <p>generated within seconds</p>
            </div>
            <div className="flex items-start gap-2">
              <div className="size-[3px] sm:size-1 lg:size-[5px] rounded-full mt-[4px] sm:mt-[9px] lg:mt-[13px] xl:mt-4 bg-white"></div>
              <p>Every userbecome DAO members via $BIT token</p>
            </div>
            {/* <p>
              In the current prototype phase our 3D Avatars can be used on these
              metaverse experiences, with many more to follow:
            </p> */}
          </div>
        </div>
      </div>
    </div>
  );
}

export default LimitedEdition;
